/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontSize: {
        'xs': '0.5rem',
        'sm': '0.625rem',
        'base': '0.75rem',
        'lg': '0.875rem',
        'xl': '1rem',
        '2xl': '1.125rem',
        '3xl': '1.25rem',
        '4xl': '1.5rem',
        '5xl': '1.75rem',
        '6xl': '2rem',
      },
      spacing: {
        '1': '0.2rem',
        '2': '0.3rem',
        '3': '0.4rem',
        '4': '0.6rem',
        '5': '0.8rem',
        '6': '1rem',
        '8': '1.5rem',
        '10': '2rem',
        '12': '2.5rem',
        '16': '3rem',
      },
      width: {
        'icon-sm': '0.75rem',
        'icon-base': '1rem',
        'icon-lg': '1.25rem',
        'logo-sm': '1.5rem',
        'logo-base': '2rem',
        'logo-lg': '2.5rem',
      },
      height: {
        'icon-sm': '0.75rem',
        'icon-base': '1rem',
        'icon-lg': '1.25rem',
        'logo-sm': '1.5rem',
        'logo-base': '2rem',
        'logo-lg': '2.5rem',
      },
      fontSize: {
        'xs': '0.5rem',
        'sm': '0.625rem',
        'base': '0.75rem',
        'lg': '0.875rem',
        'xl': '1rem',
        '2xl': '1.125rem',
        '3xl': '1.25rem',
        '4xl': '1.5rem',
        '5xl': '1.75rem',
        '6xl': '2rem',
      },
      spacing: {
        '1': '0.2rem',
        '2': '0.3rem',
        '3': '0.4rem',
        '4': '0.6rem',
        '5': '0.8rem',
        '6': '1rem',
        '8': '1.5rem',
        '10': '2rem',
        '12': '2.5rem',
        '16': '3rem',
      },
      width: {
        'icon-sm': '0.75rem',
        'icon-base': '1rem',
        'icon-lg': '1.25rem',
        'logo-sm': '1.5rem',
        'logo-base': '2rem',
        'logo-lg': '2.5rem',
      },
      height: {
        'icon-sm': '0.75rem',
        'icon-base': '1rem',
        'icon-lg': '1.25rem',
        'logo-sm': '1.5rem',
        'logo-base': '2rem',
        'logo-lg': '2.5rem',
      },
      animation: {
        'spin': 'spin 4s linear infinite',
      },
    },
  },
  plugins: [],
};
